spring.datasource.url=jdbc:postgresql://localhost:5432/newsdigest
spring.datasource.username=postgres
spring.datasource.password=Anush25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret=ThisIsAVeryLongSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong1234567890
jwt.expiration=86400000


spring.application.name=news-digest-backend
